## Pandas Übungen

Das folgende Jupyter Notebook enthält Übungen zum Thema
Pandas Series und DataFrame.
Manche Übungen enthalten Kontrollfragen. Diese sind direkt im Notebook
innerhalb einer Markdownzelle zu beantworten.

Importiere hier alle benötigten Python Packages
* Numpy (mit dem Aliasnamen **np**)
* pandas (mit dem Aliasnamen **pd**)

In [96]:
import numpy as np
import  pandas as pd

gebe für alle importieren Pakages die verwendete Versionummer aus.

Dazu musst du herausfinden wie die Version eines Python Packages ausgelesen werden kann.

In [97]:
print(np.__version__)
print(pd.__version__)

2.2.6
2.3.3

## Übungen zu Pandas Series

Erzeuge eine Pandas Series mit den Werten 1,2,3,4,5.

Gib folgende Werte aus:
* das Series Objekt aus.
* die Werte (values) des Objektes
* den Index des Objektes

Beantworte folende Fragen:

* Aus welchen Werten besteht der Index der Series wenn kein Index explizit angegeben wird?

In [98]:
ps = pd.Series([1,2,3,4,5])
ps

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [99]:
ps.values

array([1, 2, 3, 4, 5])

In [100]:
ps.index

RangeIndex(start=0, stop=5, step=1)

*integer Werte, beginnend von 0*

verwende das Series Objekt aus der vorherigen Zelle, selektiere folgende Werte:
* die ersten 3 Werte und gib sie aus.
* das erste Element und gib es aus

Beantworte folgende Fragen:
* Wie unterscheiden sich die Datentypen des Rückgabewertes wenn mehrere/nur ein Element selektiert werden?

In [101]:
ps[:3].values

array([1, 2, 3])

In [102]:
ps[0]

np.int64(1)

*array bei mehreren, np.int64 bei nur einem*

Erzeuge eine Pandas Series mit den Werten 1,2,3,4,5. und dem Index: A,B,C,D,E

Gib folgende Werte aus:
* das Series Objekt aus.
* die Werte (values) des Objektes
* den Index des Objektes

In [103]:
ps = pd.Series(data=[1,2,3,4,5], index=["A", "B", "C", "D", "E"])
ps

A    1
B    2
C    3
D    4
E    5
dtype: int64

In [104]:
ps.values

array([1, 2, 3, 4, 5])

In [105]:
ps.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

verwende das Series Objekt aus der vorherigen Zelle, selektiere folgende Werte und gib diese aus:

* Index = a
* Index = a,b
* Index von b...d

In [106]:
ps["A"]

np.int64(1)

In [107]:
ps[["A", "B"]]

A    1
B    2
dtype: int64

In [108]:
ps["A":"D"]

A    1
B    2
C    3
D    4
dtype: int64

Erzeuge 2 Series Objekte s1, s2 <br>
s1: Werte: 1,2,3, Index: a,b,c <br>
s2: Werte: 4,5,6, Index: a,b,c <br>

Erstelle ein neues Series Objekt indem die beiden Series Objekte s1 und s2 addiert werden

Beantworte folgende Fragen:
* Wie sieht das Series Objekt aus welches durch Addition der beiden anderen entstanden ist.

In [109]:
s1 = pd.Series(data=[1,2,3], index=["a","b","c"])
s2 = pd.Series(data=[4,5,6], index=["a","b","c"])

s1 + s2

a    5
b    7
c    9
dtype: int64

Erzeuge 2 Series Objekte s1, s2 <br>
s1: Werte: 1,2,3, Index: a,b,c <br>
s2: Werte: 4,5,6, Index: d,e,f <br>

Erstelle ein neues Series Objekt indem die beiden Series Objekte s1 und s2 addiert werden

Beantworte folgende Fragen:
* Wie sieht das Series Objekt aus welches durch Addition der beiden anderen entstanden ist.
* Was ist hier anders im Vergleich zur vorherigen Aufgabe?

In [110]:
s1 = pd.Series(data=[1,2,3], index=["a","b","c"])
s2 = pd.Series(data=[4,5,6], index=["d","e","f"])

s1 + s2

a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
f   NaN
dtype: float64

*alle werte sind NaN?*

Erzeuge 2 Series Objekte s1, s2 <br>
s1: Werte: 1,2,3, Index: a,b,c <br>
s2: Werte: 4,5,6, Index: a,b,c <br>

Erstelle ein neues Series Objekt indem die beiden Series Objekte s1 und s2 aneinandergefügt werden (concat)

Selektiere alle Elemente mit index='a'

Beantworte folgende Fragen:
* Wie verhalten sich die Elemente und Indizes des Series Objektes
* Was passiert wenn mehrere Elemente innerhalb der Series den gleichen Index besitzen und selektiert werden?
* Können die Elemente auch mit einem numerischen Index selektiert werden, obwohl der angegebene Index aus Buchstaben besteht?

In [111]:
s1 = pd.Series(data=[1,2,3], index=["a","b","c"])
s2 = pd.Series(data=[4,5,6], index=["a","b","c"])

sc = pd.concat((s1,s2))
sc

a    1
b    2
c    3
a    4
b    5
c    6
dtype: int64

*1. sie werden aneinander gehängt* \
*2. werden nicht überschrieben* \
*3. ja, mit sc.iloc[0]*

Erzeuge 2 Series Objekte s1, s2 <br>
s1: Werte: 1,2,3, Index: a,b,c <br>
s2: Werte: 4,5,6, Index: d,e,f <br>

Erstelle ein neues Series Objekt indem die beiden Series Objekte s1 und s2 aneinandergefügt werden (concat)

In [112]:
s1 = pd.Series(data=[1,2,3], index=["a","b","c"])
s2 = pd.Series(data=[4,5,6], index=["d","e","f"])

pd.concat((s1, s2))

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

Erstelle aus folgendem Python Dictionary eine Pandas Series und gib diese aus.

```Python
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
```

In [113]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}

population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

Erstelle folgendes Python Dictionary und folgende Python Liste mit Indizes
Anschließend erzeuge ein Series Objekt aus dem Dictionary und der Liste als Indexinformation.

```Python
python_dict = {0 : 'a',
               1 : 'b',
               2 : 'c'}
python_list = [1,2]
```

Beantworte folgende Fragen:
* wieviel Elemente besitzt das Series Objekt
* welche Elemente werden dem Series Objekt aus dem Dictionary hinzugefügt
* welche Elemente werden dem Series Objekt nicht hinzugefügt

In [114]:
python_dict = {0 : 'a',
               1 : 'b',
               2 : 'c'}
python_list = [1,2]
series = pd.Series(index=python_list, data=python_dict)
series

1    b
2    c
dtype: object

*1. 2 Elemente* \
*2. b und c* \
*3. alle ohne index (a)*

Erzeuge ein Series Objekt mit 100 zufälligen Integerwerten Bereich[100.200].
Verwende dafür ggf. auch Funktionen des numpy Packages

* Gib das größte Element aus
* Gib das kleinste Element aus
* gib die 3 größten Elemente inkl. Index aus
* gib die 5 kleinsten Elemente inkl. Index aus
* gib den Durchschnittswert der Zufallszahlen aus

Verwende dafür nur "eingebaute Funktionen" von pandas und gib an welche Funktionen verwendet wurden

In [115]:
sr = pd.Series(np.random.randint(100, 200, 100))
sr

0     113
1     155
2     157
3     156
4     192
     ...
95    181
96    160
97    110
98    119
99    103
Length: 100, dtype: int64

In [116]:
sr.max()

np.int64(199)

In [117]:
sr.min()

np.int64(101)

In [118]:
sr.nlargest(3)

17    199
78    199
35    198
dtype: int64

In [119]:
sr.nsmallest(5)

20    101
55    102
59    102
68    103
99    103
dtype: int64

In [120]:
sr.mean()

np.float64(146.09)

<hr>

## Übungen zu Pandas DataFrame

Erzeugen Sie aus folgenden Python Dictionary ein Pandas DataFrame Objekt:

```python
dictionary = {'name': ['Vinay', 'Kushal', 'Aman', 'Markus', 'Raimund', 'Dietmar'],
              'age' : [22, 25, 24, 42, 39, 56],
              'occ' : ['engineer', 'doctor', 'accountant', 'developer', 'developer', 'teacher']}
```

In [121]:
dictionary = {'name': ['Vinay', 'Kushal', 'Aman', 'Markus', 'Raimund', 'Dietmar'],
              'age' : [22, 25, 24, 42, 39, 56],
              'occ' : ['engineer', 'doctor', 'accountant', 'developer', 'developer', 'teacher']}

df = pd.DataFrame(dictionary)
df

      name  age         occ
0    Vinay   22    engineer
1   Kushal   25      doctor
2     Aman   24  accountant
3   Markus   42   developer
4  Raimund   39   developer
5  Dietmar   56     teacher

Erzeuge folgende 2 Python Listen.
Anschließend erstelle 2 Pandas Series Objekte aus diesen Listen.

Füge die beiden Pandas Series Objekte so zusammen, daß ein Pandas DataFrame entsteht.

Liste 1:
```python
liste1 = ['Hansi', 'Seppi', 'Peppi']
```

Liste 2:
```python
liste2 = [25, 26, 27]
```

In [122]:
liste1 = ['Hansi', 'Seppi', 'Peppi']
liste2 = [25, 26, 27]

df = pd.DataFrame(liste2, liste1)
df

        0
Hansi  25
Seppi  26
Peppi  27

Verwende die beiden Listen von vorher und erstelle erneut daraus ein DataFrame Objekt. Diesmal ist
aber auch ein Index anzugeben. Liste1 soll den Index 'Name' erhalten, Liste2 den Index 'Alter

In [123]:
df = pd.DataFrame({"Name": liste1, "Alter": liste2})
df

    Name  Alter
0  Hansi     25
1  Seppi     26
2  Peppi     27

Füge zum DataFrame von vorher eine 3. Spalte hinzu. 

Namen der Spalte = 'Hobby', Werte der Spalten = ['Fussball', 'Schach', 'Stricken']

In [124]:
df.insert(loc=1, column="Hobby", value=["Fußball", "Schach", "Stricken"])
df

    Name     Hobby  Alter
0  Hansi   Fußball     25
1  Seppi    Schach     26
2  Peppi  Stricken     27

In [125]:
df

    Name     Hobby  Alter
0  Hansi   Fußball     25
1  Seppi    Schach     26
2  Peppi  Stricken     27

<hr>
Erzeuge dir erneut aus diesem Python Dictionary einen DataFrame. Dieser ist für die folgenden Aufgaben zu verwenden

```python
dictionary = {'name': ['Vinay', 'Kushal', 'Aman', 'Markus', 'Raimund', 'Dietmar'],
              'age' : [22, 25, 24, 42, 39, 56],
              'occ' : ['engineer', 'doctor', 'accountant', 'developer', 'developer', 'teacher'],
              'salary' : [75000, 90000, 45000, 75000, 77000, 70000],
              'height' : [177, 192, 183, 176, 178, 187],
              'weight' : [76, 95, 93, 76, 84, 75]}
```

In [126]:
dictionary = {'name': ['Vinay', 'Kushal', 'Aman', 'Markus', 'Raimund', 'Dietmar'],
              'age' : [22, 25, 24, 42, 39, 56],
              'occ' : ['engineer', 'doctor', 'accountant', 'developer', 'developer', 'teacher'],
              'salary' : [75000, 90000, 45000, 75000, 77000, 70000],
              'height' : [177, 192, 183, 176, 178, 187],
              'weight' : [76, 95, 93, 76, 84, 75]}

df = pd.DataFrame(dictionary)

Selektiere die Spalte 'age' und den Rückgabewert sowie gib den Datetyp des Rückgabewertes aus. (nicht den eines einzelnen Wertes)

In [127]:
df.age

0    22
1    25
2    24
3    42
4    39
5    56
Name: age, dtype: int64

In [128]:
type(df.age)

pandas.core.series.Series

Selektiere die 2. Zeile des DataFrames und gib diese aus. Der Datentyp ist ebenfalls auszugeben

In [129]:
df.iloc[1]

name      Kushal
age           25
occ       doctor
salary     90000
height       192
weight        95
Name: 1, dtype: object

In [130]:
type(df.iloc[1])

pandas.core.series.Series

Selektiere die 2-4. Zeile des DataFrames und gib diese aus. Der Datentyp ist ebenfalls auszugeben

In [131]:
df.iloc[2:4]

     name  age         occ  salary  height  weight
2    Aman   24  accountant   45000     183      93
3  Markus   42   developer   75000     176      76

In [132]:
type(df.iloc[2:4])

pandas.core.frame.DataFrame

Selektiere alle Datensätze bei denen 'age>30' ist

In [133]:
df[df.age > 30]

      name  age        occ  salary  height  weight
3   Markus   42  developer   75000     176      76
4  Raimund   39  developer   77000     178      84
5  Dietmar   56    teacher   70000     187      75

Selektiere alle Datensätze bei denen 'age>30' und occ == 'developer'

In [134]:
df[(df.age > 30) & (df.occ == "developer")]

      name  age        occ  salary  height  weight
3   Markus   42  developer   75000     176      76
4  Raimund   39  developer   77000     178      84

Verschaffe dir mittels eines Einzeilers einen Überblick über die Daten des DataFrames und beantworte damit folgende Fragen:

* Anzahl Datensätze
* Mittelwert der Spaltenwerte, Min/Max-Wert der Spaltenwerte
* Werden die Überblickswerte für alle Spalten ausgegeben? Ja/Nein und begründe deine Antwort

In [135]:
df.describe()

             age        salary      height     weight
count   6.000000      6.000000    6.000000   6.000000
mean   34.666667  72000.000000  182.166667  83.166667
std    13.381579  14832.396974    6.369197   9.020347
min    22.000000  45000.000000  176.000000  75.000000
25%    24.250000  71250.000000  177.250000  76.000000
50%    32.000000  75000.000000  180.500000  80.000000
75%    41.250000  76500.000000  186.000000  90.750000
max    56.000000  90000.000000  192.000000  95.000000

*1. 6 Datensätze* \
*2.*\
    *Age: 22-56, 34.6* \
    *Salary: 45000-90000, 72000* \
    *Height: 176-192, 182.16* \
    *Weight: 75-95, 83.16* \
*3. Nein, nur bei Spalten mit numerischem Inhalt*

Gib die ersten 3 Datensätze des DataFrames aus. Verwende dafür eine entsprechende Funktion des DataFrames und nicht den Index

In [136]:
df.head(3)

     name  age         occ  salary  height  weight
0   Vinay   22    engineer   75000     177      76
1  Kushal   25      doctor   90000     192      95
2    Aman   24  accountant   45000     183      93

Erzeuge eine neue Spalte mit dem BMI (BodyMassIndex) Wert indem du folgende Formel anwendest:

$ BMI = \dfrac{Weight[kg]}{Height[m]^2} $

Der BMI soll mit einer Kommastelle angegeben werden

In [137]:
df["BMI"] = df.apply(lambda x: round(x.weight / ((x.height / 100) ** 2), 1), axis=1)

In [138]:
df

      name  age         occ  salary  height  weight   BMI
0    Vinay   22    engineer   75000     177      76  24.3
1   Kushal   25      doctor   90000     192      95  25.8
2     Aman   24  accountant   45000     183      93  27.8
3   Markus   42   developer   75000     176      76  24.5
4  Raimund   39   developer   77000     178      84  26.5
5  Dietmar   56     teacher   70000     187      75  21.4

Selektiere alle Datensätze deren BMI > 25 ist und verringere deren Einkommen um 1000 Euro.

In [139]:
df.salary = df.apply(lambda x: x.salary-1000 if x.BMI > 25 else x.salary, axis=1)

In [140]:
df

      name  age         occ  salary  height  weight   BMI
0    Vinay   22    engineer   75000     177      76  24.3
1   Kushal   25      doctor   89000     192      95  25.8
2     Aman   24  accountant   44000     183      93  27.8
3   Markus   42   developer   75000     176      76  24.5
4  Raimund   39   developer   76000     178      84  26.5
5  Dietmar   56     teacher   70000     187      75  21.4