In [2]:
import pandas as pd

In [3]:
s = pd.Series([11,2,3,4,6])
s

0    11
1     2
2     3
3     4
4     6
dtype: int64

In [4]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [5]:
s.values

array([11,  2,  3,  4,  6])

In [14]:
fruits = ["Apples", "Oranges", "Bananas", "Pears", "Melons"]
quantities = [10,9,2,40,3]

s = pd.Series(data=quantities, index=fruits, name="Quantity")
s

Apples     10
Oranges     9
Bananas     2
Pears      40
Melons      3
Name: Quantity, dtype: int64

In [15]:
s["Apples"]

np.int64(10)

In [16]:
s[["Apples", "Oranges"]]

Apples     10
Oranges     9
Name: Quantity, dtype: int64

In [17]:
s[s<10]

Oranges    9
Bananas    2
Melons     3
Name: Quantity, dtype: int64

In [18]:
s.name = "Fruits"
s

Apples     10
Oranges     9
Bananas     2
Pears      40
Melons      3
Name: Fruits, dtype: int64

In [21]:
s_new = (s+3)*4
s_new

Apples      52
Oranges     48
Bananas     20
Pears      172
Melons      24
Name: Fruits, dtype: int64

In [22]:
s+s_new

Apples      62
Oranges     57
Bananas     22
Pears      212
Melons      27
Name: Fruits, dtype: int64

In [23]:
s.apply(lambda x: x if x > 60 else x*2)

Apples     20
Oranges    18
Bananas     4
Pears      80
Melons      6
Name: Fruits, dtype: int64

In [26]:
cities = {
    "London":123,
    "Berlin":53,
    "Madrid":7291
}
cities

{'London': 123, 'Berlin': 53, 'Madrid': 7291}

In [27]:
city = pd.Series(cities)
city

London     123
Berlin      53
Madrid    7291
dtype: int64

In [37]:
more_indexes = pd.Series(cities, index=["London", "Madrid","Paris"])
more_indexes

London     123.0
Madrid    7291.0
Paris        NaN
dtype: float64

In [38]:
more_indexes.isnull()

London    False
Madrid    False
Paris      True
dtype: bool

In [40]:
more_indexes.fillna(1)

London     123.0
Madrid    7291.0
Paris        1.0
dtype: float64

In [45]:
missing = {"Paris": 4532, "London": -999}
more_indexes.fillna(missing,inplace=True)
more_indexes

London     123.0
Madrid    7291.0
Paris     4532.0
dtype: float64

# Dataframe

In [46]:
years = range(2014,2019)
years

range(2014, 2019)

In [51]:
shop1 = pd.Series([2500,2850,2430,2480,3000], index=years, name="Shop1")
shop2 = pd.Series([2501,2851,2431,2481,3001], index=years, name="Shop2")
shop3 = pd.Series([2502,2852,2432,2482,3002], index=years, name="Shop3")
shop1

2014    2500
2015    2850
2016    2430
2017    2480
2018    3000
Name: Shop1, dtype: int64

In [52]:
shops_df = pd.concat([shop1, shop2, shop3], axis=1)
shops_df

      Shop1  Shop2  Shop3
2014   2500   2501   2502
2015   2850   2851   2852
2016   2430   2431   2432
2017   2480   2481   2482
2018   3000   3001   3002

In [53]:
type(shops_df)

pandas.core.frame.DataFrame

In [55]:
shops_df.columns

Index(['Shop1', 'Shop2', 'Shop3'], dtype='object')

In [57]:
shops_df.Shop1

2014    2500
2015    2850
2016    2430
2017    2480
2018    3000
Name: Shop1, dtype: int64

In [59]:
cities = ["Zürich", "Salzburg", "Wien"]
shops_df.columns = cities

In [60]:
shops_df

      Zürich  Salzburg  Wien
2014    2500      2501  2502
2015    2850      2851  2852
2016    2430      2431  2432
2017    2480      2481  2482
2018    3000      3001  3002