In [1]:
import pandas as pd

In [2]:
s = pd.Series([11,2,3,4,6])
s

0    11
1     2
2     3
3     4
4     6
dtype: int64

In [3]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [4]:
s.values

array([11,  2,  3,  4,  6])

In [5]:
fruits = ["Apples", "Oranges", "Bananas", "Pears", "Melons"]
quantities = [10,9,2,40,3]

s = pd.Series(data=quantities, index=fruits, name="Quantity")
s

Apples     10
Oranges     9
Bananas     2
Pears      40
Melons      3
Name: Quantity, dtype: int64

In [6]:
s["Apples"]

np.int64(10)

In [7]:
s[["Apples", "Oranges"]]

Apples     10
Oranges     9
Name: Quantity, dtype: int64

In [8]:
s[s<10]

Oranges    9
Bananas    2
Melons     3
Name: Quantity, dtype: int64

In [9]:
s.name = "Fruits"
s

Apples     10
Oranges     9
Bananas     2
Pears      40
Melons      3
Name: Fruits, dtype: int64

In [10]:
s_new = (s+3)*4
s_new

Apples      52
Oranges     48
Bananas     20
Pears      172
Melons      24
Name: Fruits, dtype: int64

In [11]:
s+s_new

Apples      62
Oranges     57
Bananas     22
Pears      212
Melons      27
Name: Fruits, dtype: int64

In [12]:
s.apply(lambda x: x if x > 60 else x*2)

Apples     20
Oranges    18
Bananas     4
Pears      80
Melons      6
Name: Fruits, dtype: int64

In [13]:
cities = {
    "London":123,
    "Berlin":53,
    "Madrid":7291
}
cities

{'London': 123, 'Berlin': 53, 'Madrid': 7291}

In [14]:
city = pd.Series(cities)
city

London     123
Berlin      53
Madrid    7291
dtype: int64

In [15]:
more_indexes = pd.Series(cities, index=["London", "Madrid","Paris"])
more_indexes

London     123.0
Madrid    7291.0
Paris        NaN
dtype: float64

In [16]:
more_indexes.isnull()

London    False
Madrid    False
Paris      True
dtype: bool

In [17]:
more_indexes.fillna(1)

London     123.0
Madrid    7291.0
Paris        1.0
dtype: float64

In [18]:
missing = {"Paris": 4532, "London": -999}
more_indexes.fillna(missing,inplace=True)
more_indexes

London     123.0
Madrid    7291.0
Paris     4532.0
dtype: float64

# Dataframe

In [19]:
years = range(2014,2019)
years

range(2014, 2019)

In [20]:
shop1 = pd.Series([2500,2850,2430,2480,3000], index=years, name="Shop1")
shop2 = pd.Series([2501,2851,2431,2481,3001], index=years, name="Shop2")
shop3 = pd.Series([2502,2852,2432,2482,3002], index=years, name="Shop3")
shop1

2014    2500
2015    2850
2016    2430
2017    2480
2018    3000
Name: Shop1, dtype: int64

In [21]:
shops_df = pd.concat([shop1, shop2, shop3], axis=1)
shops_df

      Shop1  Shop2  Shop3
2014   2500   2501   2502
2015   2850   2851   2852
2016   2430   2431   2432
2017   2480   2481   2482
2018   3000   3001   3002

In [22]:
type(shops_df)

pandas.core.frame.DataFrame

In [23]:
shops_df.columns

Index(['Shop1', 'Shop2', 'Shop3'], dtype='object')

In [24]:
shops_df.Shop1

2014    2500
2015    2850
2016    2430
2017    2480
2018    3000
Name: Shop1, dtype: int64

In [25]:
cities = ["Zürich", "Salzburg", "Wien"]
shops_df.columns = cities

In [26]:
shops_df

      Zürich  Salzburg  Wien
2014    2500      2501  2502
2015    2850      2851  2852
2016    2430      2431  2432
2017    2480      2481  2482
2018    3000      3001  3002

In [38]:
new_index = ["first", "second", "third"]
population = {
    "name": ["London", "Berlin", "Rom"],
    "population" : [1,2,3],
    "country": ["UK", "DE", "IT"]
}
df_new = pd.DataFrame(population, index=new_index)
df_new

          name  population country
first   London           1      UK
second  Berlin           2      DE
third      Rom           3      IT

In [39]:
df_cities_new = pd.DataFrame(population, columns=["name", "population"], index=population["country"])
df_cities_new

      name  population
UK  London           1
DE  Berlin           2
IT     Rom           3

In [42]:
df_cities_new.iloc[[0,2]]

      name  population
UK  London           1
IT     Rom           3

In [43]:
df_cities_new.loc[["UK", "DE"]]

      name  population
UK  London           1
DE  Berlin           2

In [44]:
df_cities_new["name"]

UK    London
DE    Berlin
IT       Rom
Name: name, dtype: object

In [45]:
df_cities_new.name

UK    London
DE    Berlin
IT       Rom
Name: name, dtype: object

In [46]:
df_cities_new[["name", "population"]]

      name  population
UK  London           1
DE  Berlin           2
IT     Rom           3

In [50]:
df_cities_new["test"] = range(4,1, -1)

In [51]:
df_cities_new

      name  population  test
UK  London           1     4
DE  Berlin           2     3
IT     Rom           3     2

In [52]:
df_cities_new["population"].loc["DE"]

np.int64(2)

In [53]:
df_cities_new.sum()

name          LondonBerlinRom
population                  6
test                        9
dtype: object

In [54]:
df_cities_new["population"].sum()

np.int64(6)

In [55]:
df_cities_new

      name  population  test
UK  London           1     4
DE  Berlin           2     3
IT     Rom           3     2

In [61]:
df_cities_new.insert(loc=1, column="test2", allow_duplicates=True, value=[9,8,7])

In [62]:
df_cities_new

      name  test2  test2  population  test
UK  London      9     55           1     4
DE  Berlin      8     55           2     3
IT     Rom      7     55           3     2

# CSV Files lesen

In [95]:
personen = pd.read_csv("data/personen.csv", sep=",")
personen

    name  alter             stadt   studienfach
0   Anna     23              Wien    Informatik
1    Ben     30              Graz  Maschinenbau
2  Clara     25              Linz        Design
3  David     28              Wien    Informatik
4   Ella     22          Salzburg        Physik
5  Michi     30        Saalfelden          DSAI
6    Lea     17  St. Johann i. P.           BWL
7  Simon     18        Dofgastein    Informatik
8   Joni     17               NaN    Fotografie

In [72]:
personen.head()

    name  alter     stadt   studienfach
0   Anna     23      Wien    Informatik
1    Ben     30      Graz  Maschinenbau
2  Clara     25      Linz        Design
3  David     28      Wien    Informatik
4   Ella     22  Salzburg        Physik

In [73]:
personen.tail()

    name  alter             stadt    studienfach
3  David     28              Wien     Informatik
4   Ella     22          Salzburg         Physik
5  Michi     30        Saalfelden           DSAI
6    Lea     17  St. Johann i. P.            BWL
7  Simon     18        Dofgastein  Programmieren

In [92]:
personen.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         9 non-null      object
 1   alter        9 non-null      int64
 2   stadt        9 non-null      object
 3   studienfach  8 non-null      object
dtypes: int64(1), object(3)
memory usage: 416.0+ bytes

In [80]:
personen.describe()

           alter
count   9.000000
mean   23.333333
std     5.291503
min    17.000000
25%    18.000000
50%    23.000000
75%    28.000000
max    30.000000

In [82]:
personen.dropna()

    name  alter             stadt    studienfach
0   Anna     23              Wien     Informatik
1    Ben     30              Graz   Maschinenbau
2  Clara     25              Linz         Design
3  David     28              Wien     Informatik
4   Ella     22          Salzburg         Physik
5  Michi     30        Saalfelden           DSAI
6    Lea     17  St. Johann i. P.            BWL
7  Simon     18        Dofgastein  Programmieren

In [90]:
personen.drop(["stadt"], axis=1)

    name  alter    studienfach
0   Anna     23     Informatik
1    Ben     30   Maschinenbau
2  Clara     25         Design
3  David     28     Informatik
4   Ella     22         Physik
5  Michi     30           DSAI
6    Lea     17            BWL
7  Simon     18  Programmieren
8   Joni     17            NaN

In [91]:
personen.dropna(axis=1)

    name  alter             stadt
0   Anna     23              Wien
1    Ben     30              Graz
2  Clara     25              Linz
3  David     28              Wien
4   Ella     22          Salzburg
5  Michi     30        Saalfelden
6    Lea     17  St. Johann i. P.
7  Simon     18        Dofgastein
8   Joni     17         Taxenbach

In [96]:
personen["studienfach"].unique()

array(['Informatik', 'Maschinenbau', 'Design', 'Physik', 'DSAI', 'BWL',
       'Fotografie'], dtype=object)

In [97]:
personen.groupby("studienfach").count()

              name  alter  stadt
studienfach
BWL              1      1      1
DSAI             1      1      1
Design           1      1      1
Fotografie       1      1      0
Informatik       3      3      3
Maschinenbau     1      1      1
Physik           1      1      1

In [98]:
personen.groupby("studienfach").agg(min_valie = ("alter", "min"), max_value = ("alter", "max"))

              min_valie  max_value
studienfach
BWL                  17         17
DSAI                 30         30
Design               25         25
Fotografie           17         17
Informatik           18         28
Maschinenbau         30         30
Physik               22         22